### ISSUE TITLE
SAXParseException when running the project with Spring Boot 1.4.0

### ISSUE THREAD

**Issue by josephpford** [spring-guides/gs-integration#14]
When running the project from the commandline, I encounter a `SAXParseException`.  If I downgrade Spring Boot from 1.4.0 to 1.3.7, the problem goes away.

Steps to reproduce:
`git clone https://github.com/spring-guides/gs-integration.git`
`cd gs-integration/complete`
`gradle wrapper`
`./gradlew build`
`java -jar build/libs/gs-integration-0.1.0.jar`

Encounter Exception:
```
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 25 in XML document from class path resource [hello/integration.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 25; columnNumber: 59; cvc-complex-type.3.2.2: Attribute 'mode' is not allowed to appear in element 'file:outbound-channel-adapter'.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:180) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:207) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:144) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:127) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.load(SpringApplication.java:701) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:364) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at hello.Application.main(Application.java:8) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [gs-integration-0.1.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [gs-integration-0.1.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [gs-integration-0.1.0.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [gs-integration-0.1.0.jar:na]
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.3.2.2: Attribute 'mode' is not allowed to appear in element 'file:outbound-channel-adapter'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:458) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3237) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processAttributes(XMLSchemaValidator.java:2714) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2056) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:766) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:356) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348) ~[na:1.8.0_60]
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:429) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
	... 18 common frames omitted
```

**Comment by gregturn** [comment]
@artembilan @garyrussell Can either of you investigate?

**Comment by artembilan** [comment]
Will do right now.

**Comment by artembilan** [comment]
According to this: https://github.com/spring-projects/spring-boot/commit/c06828558609d2da58fa9f45dff1f1095b93778c

there is no `spring-integration-file` jar in the classpath:
```
BOOT-INF\lib\spring-integration-core-4.3.1.RELEASE.jar
BOOT-INF\lib\spring-integration-feed-4.3.1.RELEASE.jar
BOOT-INF\lib\spring-integration-java-dsl-1.1.3.RELEASE.jar
BOOT-INF\lib\spring-integration-jmx-4.3.1.RELEASE.jar
```
in contradistinction to this in case of Boot 1.3.x:
```
lib\spring-integration-core-4.2.9.RELEASE.jar
lib\spring-integration-feed-4.2.9.RELEASE.jar
lib\spring-integration-file-4.2.9.RELEASE.jar
lib\spring-integration-http-4.2.9.RELEASE.jar
lib\spring-integration-ip-4.2.9.RELEASE.jar
lib\spring-integration-stream-4.2.9.RELEASE.jar
```

So, `gs-integration` has to be fixed with extra dependency.

Will PR that soon.

**Comment by artembilan** [comment]
Spring Boot issue on the matter for cross-linking: https://github.com/spring-projects/spring-boot/issues/5528

**Comment by josephpford** [comment]
Very impressed at your team's response times.
